const hourEl = document.querySelector('.hour')
const minuteEl = document.querySelector('.minute')
const secondEl = document.querySelector('.second')
const timeEl = document.querySelector('.timeEl')
const dateEl = document.querySelector('.dateEl')
const toggle = document.querySelector('.toggle')